# Generated by Django 3.2.4 on 2021-06-06 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_auto_20210605_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_de_compra',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='farmacia.produto'),
        ),
    ]
